services:
  retailconnectkeycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak_with_jwks_example
    ports:
      - 8081:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./jwedemo-realm-export.json:/opt/keycloak/data/import/jwedemo-realm-export.json
    command: start-dev --import-realm  --log-level="INFO,org.apache.http.headers:DEBUG,org.apache.http.wire:DEBUG,org.keycloak.authentication.authenticators.client:TRACE,org.keycloak.keys.infinispan:DEBUG"
