version: "3.9"
services:
  retailconnectkeycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    container_name: keycloak_with_jwks_example
    ports:
      - 8081:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./jwedemo-realm-export.json:/opt/keycloak/data/import/jwedemo-realm-export.json
    command: start-dev --import-realm
